In [25]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf

import model_only as lib
import numpy as np


print(np.log(8))
# testing batch gather
sess = tf.Session()
x = tf.constant([[11, 1],[12,2],[13,3]])
idx = tf.constant([0,1,1])
result = lib.batch_gather(x,idx)
expected_result = [11, 2, 3]
with sess.as_default():
    actual_result = result.eval()
    print(actual_result)
    # add an assert if expected result does not make actual.


    
# l = tf.constant([1, -1, 0, 1, -1], dtype=tf.float64)
# ys = tf.constant([-1,1], dtype=tf.float64)
# eq = tf.map_fn(lambda y: lib.equal_sign(y, l), ys)
# expectedV = [[-1,  1,  0, -1,  1], [ 1, -1, -0,  1, -1]]
# with sess.as_default():
#   actualV = eq.eval()


def batch_gather(x,idx):
    # x : [numRows, numCols]
    # idx = [numRows]
    # collects the column of x for each row as specified in the idx. 
    cat_idx = tf.concat([tf.expand_dims(tf.range(0, tf.shape(x)[0]),1), tf.expand_dims(idx,1)], axis=1)
    return tf.gather_nd(x, cat_idx)

def getTheta(thetas, y, numYs=3):
     if numYs == 2:
        return tf.cond(y < 0, lambda: thetas[0], lambda: thetas[1])
     return thetas[tf.cast(y, tf.int32)]
   #return batch_gather(thetas, y)

thetas =  tf.constant([[1, -1, 0], [1, -1, -3], [0, 0, -4]], dtype=tf.float64)
ys = tf.constant([0,1,2], dtype=tf.float64)
log_pt = tf.map_fn(lambda y: getTheta(thetas, y), ys)
proj = tf.reduce_sum(thetas[0]) + tf.reduce_sum(thetas[1])
with sess.as_default():
  p = proj.eval()
  print(p)
  vv = log_pt.eval()
  print(vv)


2.07944154168
[11  2  3]
-3.0
[[ 1. -1.  0.]
 [ 1. -1. -3.]
 [ 0.  0. -4.]]
